#GFSK_Rb250Fd250
{"model": "sx1231",
"description": {"modulation":"GFSK", "speed": "100kb/s","rx_bw":"00", "deviation":"5kHz"},
"registers":
"""
# RH_RF69_REG_02_DATAMODUL
RH_RF69_DATAMODUL_DATAMODE                          = 0x60
RH_RF69_DATAMODUL_DATAMODE_PACKET                   =0x00
RH_RF69_DATAMODUL_DATAMODE_CONT_WITH_SYNC           =0x40
RH_RF69_DATAMODUL_DATAMODE_CONT_WITHOUT_SYNC        =0x60
RH_RF69_DATAMODUL_MODULATIONTYPE                    =0x18
RH_RF69_DATAMODUL_MODULATIONTYPE_FSK                =0x00
RH_RF69_DATAMODUL_MODULATIONTYPE_OOK                =0x08
RH_RF69_DATAMODUL_MODULATIONSHAPING                 =0x03
RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_NONE        =0x00
RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_BT1_0       =0x01
RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_BT0_5       =0x02
RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_BT0_3       =0x03
RH_RF69_DATAMODUL_MODULATIONSHAPING_OOK_NONE        =0x00
RH_RF69_DATAMODUL_MODULATIONSHAPING_OOK_BR          =0x01
RH_RF69_DATAMODUL_MODULATIONSHAPING_OOK_2BR         =0x02

# RH_RF69_REG_37_PACKETCONFIG1
RH_RF69_PACKETCONFIG1_PACKETFORMAT_VARIABLE         =0x80
RH_RF69_PACKETCONFIG1_DCFREE                        =0x60
RH_RF69_PACKETCONFIG1_DCFREE_NONE                   =0x00
RH_RF69_PACKETCONFIG1_DCFREE_MANCHESTER             =0x20
RH_RF69_PACKETCONFIG1_DCFREE_WHITENING              =0x40
RH_RF69_PACKETCONFIG1_DCFREE_RESERVED               =0x60
RH_RF69_PACKETCONFIG1_CRC_ON                        =0x10
RH_RF69_PACKETCONFIG1_CRCAUTOCLEAROFF               =0x08
RH_RF69_PACKETCONFIG1_ADDRESSFILTERING              =0x06
RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NONE         =0x00
RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NODE         =0x02
RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NODE_BC      =0x04
RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_RESERVED     =0x06


CONFIG_FSK = RH_RF69_DATAMODUL_DATAMODE_PACKET | RH_RF69_DATAMODUL_MODULATIONTYPE_FSK | RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_NONE
CONFIG_GFSK =RH_RF69_DATAMODUL_DATAMODE_PACKET | RH_RF69_DATAMODUL_MODULATIONTYPE_FSK | RH_RF69_DATAMODUL_MODULATIONSHAPING_FSK_BT1_0)
CONFIG_OOK =RH_RF69_DATAMODUL_DATAMODE_PACKET | RH_RF69_DATAMODUL_MODULATIONTYPE_OOK | RH_RF69_DATAMODUL_MODULATIONSHAPING_OOK_NONE)

# Choices for RH_RF69_REG_37_PACKETCONFIG1:
CONFIG_NOWHITE =RH_RF69_PACKETCONFIG1_PACKETFORMAT_VARIABLE | RH_RF69_PACKETCONFIG1_DCFREE_NONE | RH_RF69_PACKETCONFIG1_CRC_ON | RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NONE)
CONFIG_WHITE =RH_RF69_PACKETCONFIG1_PACKETFORMAT_VARIABLE | RH_RF69_PACKETCONFIG1_DCFREE_WHITENING | RH_RF69_PACKETCONFIG1_CRC_ON | RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NONE)
CONFIG_MANCHESTER =RH_RF69_PACKETCONFIG1_PACKETFORMAT_VARIABLE | RH_RF69_PACKETCONFIG1_DCFREE_MANCHESTER | RH_RF69_PACKETCONFIG1_CRC_ON | RH_RF69_PACKETCONFIG1_ADDRESSFILTERING_NONE)
"""
def operating_mode(mode):
    return(0x00)

def packet_settings(config):
    return(0x40)


  [(2,operating_mode("gfsk")), 
   (3,0x00),                    #RegBitrateMsb
   (4,0x80),                    #RegBitrateLsb
   (5,0x10),                    #RegFdevMsb
   (6, 0x00),                   #RegFdevLsb
   (0x19, 0xe0),                #RegRxBw
   (0x1a,0xe0),                 #RegAfcBw
   (0x37,                       #RegPacketConfig1
   packet_settings("white"))]
}
